#!/bin/sh

Usage() {
  cat <<EOF
    ___________ _   ____
   / ____|__  // | / / /
  / /     /_ </  |/ / /
 / /___ ___/ / /|  / /___
 \____//____/_/ |_/_____/

 Niall J. Bourke Imperial College London Feb 2019
 n.bourke@imperial.ac.uk
 v2.1 (04/07/2019)


usage:  bids_2_proc -i <project_ID> -c <config.json>

e.g. bids_2_proc -i DREAM -c CIF_congig.json

* Check output from preproc step
* Subjects should be labled by their CIF ID
* Scanning sessions should be inside the CID ID level
* Meta data regarding scan sessions and dates should be saved to a json.

EOF
  exit 1
}

if [  $# -le 3 ];
  then
  Usage
  exit 1
 fi

while [ $# -ge 3 ];
do
  case "$1" in

		-i)
					project=$2;
          con=$4
					shift;;

  esac
  shift
done


  echo " Input job = $project "

# Initial Setup
module load mricogl
dependencies=/rds/general/project/c3nl_shared/live/dependencies
config=${dependencies}/${con}

### HARDCODED ###
wd=/rds/general/project/c3nl_djs_imaging_data/live/data/raw/
out=/rds/general/project/c3nl_djs_imaging_data/live/data/
### MAKE BETTER ###
echo "" > $wd/jobs/bids_${project}.txt

echo "project is $project"
echo "config is $config"


cd ${wd}/${project}

# Loop over data
for subject in `ls -d ${wd}/${project}/*/`; do
  sub=`basename $subject`
  echo "organising: $sub ... "

  for session in `ls -d ${wd}/${project}/${sub}/*/`; do
    sesh=`basename $session`
    echo "in session: $sesh"

    for sequence in `ls -d ${wd}/${project}/${sub}/${sesh}/scans/*/`; do
    scan=`basename $sequence`
    mkdir -p ${wd}/${project}/${sub}/${sesh}/${scan}/DICOM
    mv ${wd}/${project}/${sub}/${sesh}/scans/${scan}/resources/DICOM/files/* ${wd}/${project}/${sub}/${sesh}/${scan}/DICOM/

    dcm2niix ${wd}/${project}/${sub}/${sesh}/${scan}

    for key in $(cat $config | jq '.descriptions | to_entries[] | .key'); do
      sd=$(cat $config | jq -r '.descriptions['$key'].criteria.SeriesDescription');

      #Match data with index file
      if [[ $scan = $sd ]]; then
        dt=$(cat $config | jq -r '.descriptions['$key'].dataType')
        ml=$(cat $config | jq -r '.descriptions['$key'].modalityLabel')
        cl=$(cat $config | jq -r '.descriptions['$key'].customLabels')

        mkdir -p ${out}/sourcedata/sub-${sub}/ses-${sesh}/${dt}/${ml}/

        for scanData in `ls ${wd}/${project}/${sub}/${sesh}/${scan}/`; do
          sdata=`basename $scanData`
          suf=$(echo $sdata | cut -d'.' -f2,3)

          for zz in `ls ${wd}/${project}/${sub}/${sesh}/${scan}/*.${suf}`; do
          cp ${zz} ${out}/sourcedata/sub-${sub}/ses-${sesh}/${dt}/${ml}/sub-${sub}_ses-${sesh}_${cl}.${suf}
          done
        done

      continue
      fi
      done

    done
    # copy metaData
    cp ${wd}/${project}/${sub}/${sesh}/metaData* ${out}/sourcedata/sub-${sub}/ses-${sesh}/
  done
done

# Share the data love
chmod -R +rwx ${out}/sourcedata/*
